import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatCheckboxModule,
  MatGridListModule,
  MatFormFieldModule,
  MatInputModule,
  MatMenuModule,
  MatRippleModule,
  MatAutocompleteModule,
  MatSelectModule,
  MatSnackBarModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatTableModule,
  MatDividerModule,
  MatRadioModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatDialogModule,
  MatTooltipModule
} from '@angular/material';

@NgModule({
    imports: [
      MatButtonModule,
      MatCheckboxModule,
      MatGridListModule,
      MatFormFieldModule,
      MatInputModule,
      MatMenuModule,
      MatRippleModule,
      MatAutocompleteModule,
      MatSelectModule,
      MatTableModule,
      MatPaginatorModule,
      MatSnackBarModule,
      MatDialogModule,
      MatDividerModule,
      MatRadioModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatProgressSpinnerModule,
      MatTooltipModule
    ],
    exports: [
      MatButtonModule,
      MatCheckboxModule,
      MatGridListModule,
      MatFormFieldModule,
      MatInputModule,
      MatMenuModule,
      MatRippleModule,
      MatAutocompleteModule,
      MatSelectModule,
      MatTableModule,
      MatPaginatorModule,
      MatSnackBarModule,
      MatDialogModule,
      MatDividerModule,
      MatRadioModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatProgressSpinnerModule,
      MatTooltipModule
    ],
})
export class MaterialModule { }
